name: Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, pypy, pypy3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Test with inv
        run: inv cover qa
  bench:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout ${{ github.base_ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref}}
          path: base
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref}}
          path: ref
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "base[ci]"
      - name: Benchmarks for ${{ github.base_ref }}
        run: inv benchmark --max-time 4 --save
      - name: Install ref dependencies
        run: pip install -e "ref[ci]"
      - name: Benchmarks for ${{ github.ref }}
        run: inv benchmark --max-time 4 --compare
